services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - cloud-network

  backend:
    build: ./backend
    environment:
      POSTGRES_PORT: 5432
    ports:
      - "8081:8081"
    networks:
      - cloud-network
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:18-alpine
    container_name: cloud-db
    environment:
      POSTGRES_DB: tasks
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./sql-data:/var/lib/postgresql/18/docker
    networks:
      - cloud-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tasks"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  sql-data:

networks:
  cloud-network:
    driver: bridge
